= CDC Backfill CLI

When CDC is enabled on a topic, the data topic doesn't contain any data from before CDC was enabled.
The backfill CLI solves this problem by exporting the table's primary key to a Comma Separated Values (CSV) file, storing the CSV file on disk, and sending the primary key from the CSV file to the event topic.
The Cassandra Source Connector reads the primary key from the event topic and populates the data topic with historical data.

Developers can also use the backfill CLI to trigger change events for downstream applications without having to insert new data.

== Installation

The CDC backfill CLI is distributed both as a jar file and as a Pulsar-admin extension.
Both artifacts are built with Gradle.

To build the CLI, run the following commands:
[tabs]
====
Gradle::
+
--
[source,bash]
----
git clone git@github.com:datastax/cdc-apache-cassandra.git
cd cdc-apache-cassandra
./gradlew backfill-cli:assemble
----
--
Result::
--
[source,bash]
----
BUILD SUCCESSFUL in 37s
17 actionable tasks: 15 executed, 2 up-to-date
----
--
====

Gradle generates two main artifacts:
* An uber jar file containing the CLI and all its dependencies: backfill-cli/build/libs/backfill-cli-<version>-all.jar
* A NAR archive that wraps the CLI as a Pulsar-admin Extension: backfill-cli/build/libs/pulsar-cassandra-admin-<version>-nar.nar

To run the standalone Java application, use the following command:
[source,bash]
----
java -jar backfill-cli/build/libs/backfill-cli-<version>-all.jar --data-dir target/export --export-host 127.0.0.1:9042 \
 --export-username cassandra --export-password cassandra --keyspace ks1 --table table1
----

To run the Pulsar-admin extension:
. Move the generated NAR archive to the /cliextensions folder of your Pulsar installation (e.g. /pulsar/cliextensions).
. Modify the client.conf file of your Pulsar installation to include: `customCommandFactories=cassandra-cdc`.
. Run the following command:
[source,bash]
----
./bin/pulsar-admin cassandra-cdc backfill --data-dir target/export --export-host 127.0.0.1:9042 \
 --export-username cassandra --export-password cassandra --keyspace ks1 --table table1
----

== Parameters reference
[cols=2*,options="header"]
|===
|Parameter
|Behavior

|--data-dir, -d
|The directory where data will be exported to and imported from
|--events-topic-prefix
|The event topic name prefix. The `<keyspace_name>.<table_name>` is
appended to that prefix to build the topic name. The default value
is `events-`.
|--export-bundle
|The path to a secure connect bundle to connect to the Cassandra
cluster, if that cluster is a DataStax Astra cluster. Options
|--export-host and --export-bundle are mutually exclusive.
|--export-consistency
|The consistency level to use when exporting data. The default is
LOCAL_QUORUM.
|--export-dsbulk-option
|An extra DSBulk option to use when exporting. Any valid DSBulk
option can be specified here, and it will passed as is to the
DSBulk process. DSBulk options, including driver options, must be
passed as
'--long.option1.name=<value1>|--long.option2.name=<value2>'. Short
options are not supported.
|--export-host
|The host name or IP and, optionally, the port of a node from the
Cassandra cluster. If the port is not specified, it will default
to 9042.
|--export-max-concurrent-files
|The maximum number of concurrent files to write to. Must be a
positive number or the special value AUTO. The default is AUTO.
|--export-max-concurrent-queries
|The maximum number of concurrent queries to execute. Must be a
positive number or the special value AUTO. The default is AUTO.
|--export-password
|The password to use to authenticate against the origin cluster.
|--export-protocol-version
|The protocol version to use to connect to the Cassandra cluster,
e.g. 'V4'. If not specified, the driver will negotiate the highest
version supported by both the client and the server.
|--export-username
|The username to use to authenticate against the origin cluster.
|--keyspace, -k
|The name of the keyspace where the table to be exported exists
|--max-rows-per-second
|The maximum number of rows per second to read from the Cassandra
table. Setting this option to any negative value or zero will
disable it. The default is -1.
Default: 0
|--table, -t
|The name of the table to export data from for cdc back filling
|===

== client.conf parameters

== Limitations