= CDC for Cassandra Events 

The Datastax CDC for Cassandra agent pushes the mutation primary key for the CDC-enabled table into the Apache Pulsar events topic (also called the dirty topic). The messages in the data topic (or clean topic) are a JSON representation of AVRO Generic Record by default, using a logical type for the following types:

* `Date`
* `Decimal`
* `Duration`
* `Timestamp`
* `Varint`
* `Uuid`, `timeuuid`

See https://avro.apache.org/docs/current/spec.html[AVRO Generic Record] for more info on AVRO. 

== Change Event’s Key

For a given table, the change event’s key will have a structure that contains a field for each column in the primary key of the table at the time the event was created.

[SOURCE]
----
{
  "primaryKey": {
    "partitionKey": [
      "key"
    ]
  },
  "columnDefinitions": [
    {
      "name": "key",
      "typeDefinition": "text",
      "static": false
    },
    {
      "name": "c1",
      "typeDefinition": "text",
      "static": false
    }
  ]
}
----

== `INSERT` Event

When an `INSERT` statement is executed, the full row at the time of replication will be visible, with all regular columns.

[SOURCE]
----
INSERT INTO ks1.tbl1 (key, c1) VALUES (`32a`, `1234a`)
INSERT INTO ks1.tbl1 (key, c1) VALUES (`3`, `bob3`)
----

Enter `select * from ks1.tbl1;` to see the inserted values:

[SOURCE]
----
key | c1
-----+-------
 32a | 1234a
   3 |  bob3
----

A JSON representation of the AVRO Generic Record schema would look like this:

[SOURCE]
----
{
  "primaryKey": {
    "partitionKey": [
      "key"
    ]
  },
  "columnDefinitions": [
    {
      "name": "key",
      "typeDefinition": "text",
      "static": false
    },
    {
      "name": "c1",
      "typeDefinition": "text",
      "static": false
    }
  ]
}
----

Enter `DESC SCHEMA` to describe all non-system objects in the cluster. Our output looks like this:

[SOURCE]
----
CREATE KEYSPACE ks1 WITH replication = {'class': 'NetworkTopologyStrategy', 'us-east1': '3'}  AND durable_writes = true;

CREATE TABLE ks1.tbl1 (
    key text PRIMARY KEY,
    c1 text
) WITH additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';
----

== `UPDATE` Event

When an `UPDATE` event is executed, the last visible state at the time of the replication will be displayed (not a before/after picture).

[SOURCE]
----
{
   _id: { < Resume Token > },
   operationType: 'update',
   clusterTime: <Timestamp>,
   ns: {
      db: 'engineering',
      coll: 'users'
   },
   documentKey: {
      _id: ObjectId("58a4eb4a30c75625e00d2820")
   },
   updateDescription: {
      updatedFields: {
         email: 'alice@10gen.com'
      },
      removedFields: ['phoneNumber'],
      truncatedArrays: [ {
         "field" : "vacation_time",
         "newSize" : 36
      } ]
   }
}
----

== `DELETE` Event

When a `DELETE` event is executed, Pulsar will return a tombstone message with the key matching the C* primary key and a null payload. The null payload will be deleted by Elasticsearch or any other sink connector. 

[SOURCE]
----
{
   _id: { < Resume Token > },
   operationType: 'delete',
   clusterTime: <Timestamp>,
   ns: {
      db: 'engineering',
      coll: 'users'
   },
   documentKey: {
      _id: ObjectId("599af247bb69cd89961c986d")
   }
}
----

=== Check the Source Connector logs
If you're having issues with CDC events, check the source connector logs and data topic schema.

On the pulsar broker, for `keyspace=ks1` and `table=table4`:

[SOURCE]
----
cat /pulsar/logs/functions/public/default/cassandra-source-ks1-table4/cassandra-source-ks1-table4-0.log
----

=== Check the data topic schema

Ensure the data topic schema matches your current CQL schema with `bin/pulsar-admin schemas get "persistent://public/default/data-ks1.table4"`.

[SOURCE]
----
{
  "version": 0,
  "schemaInfo": {
    "name": "data-ks1.table4",
    "schema": {
      "key": {
        "name": "table4",
        "schema": {
          "type": "record",
          "name": "table4",
          "namespace": "ks1",
          "doc": "Table ks1.table4",
          "fields": [
            {
              "name": "a",
              "type": "string"
            },
            {
              "name": "b",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        },
        "type": "AVRO",
        "properties": {}
      },
      "value": {
        "name": "table4",
        "schema": {
          "type": "record",
          "name": "table4",
          "namespace": "ks1",
          "doc": "Table ks1.table4",
          "fields": [
            {
              "name": "c",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "d",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        },
        "type": "AVRO",
        "properties": {}
      }
    },
    "type": "KEY_VALUE",
    "properties": {
      "key.schema.name": "table4",
      "key.schema.properties": "{}",
      "key.schema.type": "AVRO",
      "kv.encoding.type": "SEPARATED",
      "value.schema.name": "table4",
      "value.schema.properties": "{}",
      "value.schema.type": "AVRO"
    }
  }
}
----


