= Cassandra Source Connector FAQs

If you are new to DataStax Cassandra Source Connector (CSC), please read the following FAQs.

== Introduction

=== What is DataStax CSC?

The Alpha release of the Cassandra Source Connector (CSC) is a new, open-source product from DataStax.

With CDC, your apps can consume data from an Apache Cassandra table and submit the updates onto a Pulsar topic.  This topic can then be consumed by external targets such as Elastic, Snowflake, and other platforms. By design, the CSC is meant to be a simple connector with a 1:1 correspondence between a Cassandra table and a single Pulsar topic.

The CSC is composed of two parts:

* The Cassandra Source Connector, which transmits Change Data Capture (CDC) updates from the Cassandra table to the streaming service.
* The Pulsar CSC Connector, which verifies the CSC events and stores the final data changes into a Data topic.

=== What are the system requirements for the CSC?

The CSC requires additional resources depending on your write throughput.

For each Cassandra write, each Cassandra replica sends one message to your Pulsar service, and executes at least one QUORUM read on your Cassandra cluster.

=== What components and features are provided by Cassandra Source Connector?

Cassandra Source Connector provides:

* Cassandra, Elastic, Snowflake, Kinesis, Kafka, and JDBC connectors
* A management dashboard
* A monitoring and alerting system

=== Which versions of Apache Pulsar does DataStax Cassandra Source Connector support?

Cassandra Source Connector supports Apache Pulsar 2.7.0 and later.

=== What does the CSC provide that is not provided by Apache Pulsar?

DataStax Cassandra Source Connector implements the reverse of the DataStax Cassandra Source Connector, which stores Pulsar topic updates into Cassandra.  The CSC takes data from a Cassandra table and stores that data into a Pulsar topic.  From there, the data can be published to external platforms like Snowflake, Elastic, and so on.

=== Is DataStax Cassandra Source Connector an open-source project?

Yes, DataStax Cassandra Source Connector is open source under the Apache 2.0 License. See the <<gitHubRepos,repos FAQ>>.

=== Which Kubernetes platforms are supported by the CSC?

The CSC supports most commonly used Kubernetes platforms, including:

* Minikube
* K8d
* Kind
* Google Kubernetes Engine (GKE)
* Microsoft Azure Kubernetes Service
* Amazon Kubernetes Service (AKS), and other commonly used platforms.

[#gitHubRepos]
=== Where is the CSC public GitHub repo?

The source for this FAQ and related CSC documents are co-located with the Cassandra Source Connector repo code, examples, and additional documentation: access the [repo here](https://github.com/riptano/cdcrep).

== Installation

=== Is there a prerequisite version of Java needed for the DataStax Cassandra Source Connector installation?

The DataStax Cassandra Source Connector distribution is designed for Java 11. However, because the product releases Docker images, you do not need to install Java (8 or 11) in advance. Java 11 is bundled in the Docker image.

=== How do I install Cassandra Source Connector?

Download the tar file from the DataStax [Downloads site](https://downloads.datastax.com/#csc). Then follow the xref:install.adoc[install] instructions. The tarball contains the Cassandra Source Connector distribution's NAR file.

=== How many Cassandra Tables can I track?

As many as your system can handle.  Note that each Cassandra table CDC events must be tracked with a separate Cassandra Source Connector.

== Tasks

=== What task can I perform in the DataStax Cassandra Source Connector Installation Console?

From the Installation Console, you can:

* Configure the CSC environment.
* View and update the CSC version and application status.
* Retrieve the host URL and generated password to launch the CSC Admin Console
* Set up and view Grafana graphs, which display metrics collected by the provided Prometheus Operator.
* Analyze the CSC to collect information you could provide for support functions.
* Sync the license that enables CSC software.
* View upstream, midstream, and downstream files used by the CSC.

=== What task can I perform in the CSC Admin Console?

From the CSC Admin Console, you can:

* Add and run Pulsar clients.
* Establish credentials for secure connections.
* Define topics that can be published for streaming apps.
* Set up Pulsar sinks that publish topics and make them available to subscribers, such as Cassandra Tables.
* Control namespaces used by Pulsar.
* Use the Admin API.

=== What is Pulsar Heartbeat?

https://github.com/datastax/pulsar-heartbeat[Pulsar Heartbeat] monitors the availability, tracks the performance, and reports failures of the Pulsar cluster. It produces synthetic workloads to measure end-to-end message pubsub latency.  Pulsar Heartbeat is a cloud-native application that can be installed by Helm within the Pulsar Kubernetes cluster.

=== What is Prometheus?

https://prometheus.io/docs/introduction/overview/[Prometheus] is an open-source tool to collect metrics on a running app, providing real-time monitoring and alerts.

=== What is Grafana?

https://grafana.com/[Grafana] is a visualization tool that helps you make sense of metrics and related data coming from your apps via Prometheus, for example.

== Pulsar Connector

=== What are the features provided by Cassandra Source Connector that are not supported in `pulsar-sink`?

* Single record acknowledgement and negative acknowledgements.
* The https://pulsar.apache.org/docs/en/2.6.2/io-overview/[Pulsar IO framework] provides many features that are not possible in Kafka, and has different compression formats and auth/security features. The features are handled by Pulsar.

=== What features are missing in Cassandra Source Connector that are provided in pulsar-sink?

* No support for `tinyint` (`int8bit`) and `smallint` (`int16bit`).
* The key is always a String, but you can write JSON inside of it.  This is supported by pulsar-sink, but not Pulsar IO.
* The value of a “message property” is always a string. For example, you cannot map the message property to `__ttl` or to `__timestamp`.
* Field names inside structures must be valid for Avro, even in case of JSON structures. For example, field names like `Int.field` (with dot) or `int field` (with space) are not valid.

== APIs

=== What client APIs does Cassandra Source Connector provide?

The same as for Apache Pulsar. See https://pulsar.apache.org/docs/en/client-libraries/.

== Next

If you haven't already, build try the CSC for yourself to to consume data from a Cassandra table and transmit the updates onto a Pulsar topic. See the xref:install.adoc[Quick Start Guide].
