= Cassandra Source Connector FAQs

If you are new to DataStax Cassandra Source Connector, these FAQs are for you.

== Introduction

=== What is DataStax Cassandra Source Connector?

The Alpha release of Cassandra Source Connector is a new, open-source product from DataStax.
With CDC, Cassyour apps can consume data from an Apache Cassandra&reg; table and put the updates onto a Pulsar topic, which in turn can write the data to external targets such as Elastic, Snowflake, and other platforms. By design, the Source component is simple, with a 1:1 correspondence between the Cassandra table and a single Pulsar topic.

=== What are the system requirements for Cassandra Data Connector?

Cassandra Source Connector requires additional resources depending on your write throughput.
For each cassandra write, each Cassandra replica send one message to your streaming platform (Pulsar
execute at least one QUORUM read on your

=== What components and features are provided by Cassandra Data Connector?

Cassandra Data Connector provides:

* Cassandra, Elastic, Snowflake, Kinesis, Kafka, and JDBC connectors
* A management dashboard
* A monitoring and alerting system

=== Which versions of Apache Pulsar does DataStax Cassandra Data Connector support?

Cassandra Data Connector supports Apache Pulsar 2.7.0 and later.

=== What does Cassandra Data Connector provide that I cannot get with open-source Apache Pulsar?

DataStax Cassandra Data Connector implements, in effect, the reverse of Apache Pulsar or DataStax CassaNdra data Connector. With CSC, the Source takes data from Cassandra and puts that date onto onto a Pulsar topic. From there, the data can be published to external platforms like Snowflake, Elastic, and so on.

=== Is DataStax Cassandra Data Connector an open-source project?

Yes, DataStax Cassandra Data Connector is open source. See the <<gitHubRepos,repos FAQ>>.

=== Which Kubernetes platforms are supported by DataStax Cassandra Data Connector?

They include Minikube, K8d, Kind, Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service, Amazon Kubernetes Service (AKS), and other commonly used platforms.

[#gitHubRepos]
=== Where is the DataStax Cassandra Data Connector public GitHub repo?

The source for this FAQs document is co-located with the Cassandra Data Connector repo code, examples, and additional documentation: access the [repo here](https://github.com/riptano/cdcrep).

== Installation

=== Is there a prerequisite version of Java needed for the DataStax Cassandra Data Connector installation?

The DataStax Cassandra Data Connector distribution is designed for Java 11. However, because the product releases Docker images, you do not need to install Java (8 or 11) in advance. Java 11 is bundled in the Docker image.

=== How do I install Cassandra Data Connector?

Download the tar file from the DataStax [Downloads site](https://downloads.datastax.com/#cdc). Then follow the xref:install.adoc[install] instructions. The tarball contains the Cassandra Data Connector distribution's NAR file.

== Tasks

=== What task can I perform in the DataStax Cassandra Data Connector Installation Console?

From the Installation Console, you can:

* Configure the DataStax Cassandra Data Connector environment
* View and update the DataStax Cassandra Data Connector version and application status
* Get the host URL and generated password to launch the DataStax Cassandra Data Connector Admin Console
* Set up and view Grafana graphs, which display metrics collected by the provided Prometheus Operator
* Analyze DataStax Cassandra Data Connector to collect information you could provide for Support
* Sync the license that enables DataStax Cassandra Data Connector software
* View upstream, midstream, and downstream files used by DataStax Cassandra Data Connector

=== What task can I perform in the DataStax Cassandra Data Connector Admin Console?

From the Admin Console, you can:

* Add and run Pulsar clients
* Establish credentials for secure connections
* Define topics that can be published for streaming apps
* Set up Pulsar sinks that publish topics and make them available to subscribers, such as for a Cassandra database table
* Control namespaces used by Pulsar
* Use the Admin API

=== What is Pulsar Heartbeat?

https://github.com/datastax/pulsar-heartbeat[Pulsar Heartbeat] monitors the availability, tracks the performance, and reports failures of the Pulsar cluster. It produces synthetic workloads to measure end-to-end message pubsub latency.  Pulsar Heartbeat is a cloud-native application that can be installed by Helm within the Pulsar Kubernetes cluster.

=== What is Prometheus?

https://prometheus.io/docs/introduction/overview/[Prometheus] is an open-source tool to collect metrics on a running app, providing real-time monitoring and alerts.

=== What is Grafana?

https://grafana.com/[Grafana] is a visualization tool that helps you make sense of metrics and related data coming from your apps via Prometheus, for example.

== Pulsar Connector

=== What are the features provided by Cassandra Data Connector that are not supported in `pulsar-sink` ?

* Single record acknowledgement and negative acknowledgements.
* The https://pulsar.apache.org/docs/en/2.6.2/io-overview/[Pulsar IO framework] provides many features that are not possible in Kafka, and has different compression formats and auth/security features. The features are handled by Pulsar.

=== What features are missing in Cassandra Data Connector that are provided in `pulsar-sink` or `kafka-sink`?

* No support for `tinyint` (`int8bit`) and `smallint` (`int16bit`).
* The key is always a String, but you can write JSON inside it; the support is implemented in pulsar-sink, but not in Pulsar IO.
* The “value” of a “message property” is always a String; for example, you cannot map the message property to `__ttl` or to `__timestamp`.
* Field names inside structures must be valid for Avro, even in case of JSON structures. For example, field names like `Int.field` (with dot) or `int field` (with space) are not valid.

== APIs

=== What client APIs does Cassandra Data Connector provide?

The same as for Apache Pulsar. See https://pulsar.apache.org/docs/en/client-libraries/.

== Next

If you haven't already, build your first app to consume data from a Cassandra table and put the updates onto a Pulsar topic.
