= Cassandra Source Connector FAQs

If you are new to DataStax Cassandra Source Connector, these FAQs are for you.

== Introduction

=== What is DataStax Cassandra Source Connector?

The Alpha release of Cassandra Source Connector is a new, open-source product from DataStax.
With CDC, Cassyour apps can consume data from an Apache Cassandra&reg; table and put the updates onto a Pulsar topic, which in turn can write the data to external targets such as Elastic, Snowflake, and other platforms. By design, the Source component is simple, with a 1:1 correspondence between the Cassandra table and a single Pulsar topic.

=== What are the system requirements for Cassandra Source Connector?

Minimum system requirement are:
* Cassandra 3.11 or 4.0+,
* Apache Pulsar 2.8.1+

=== What are the Cassandra Source Connector limitations?

The Cassandra Source Connector:
* Does not replay batch updates
* Does not manage table truncates
* Does not sync data available before starting the CDC producer.
* Does not manage TTL
* Does not support range deletes

=== Is DataStax Cassandra Data Connector an open-source project?

Yes, DataStax Cassandra Data Connector is open source. See the <<gitHubRepos,repos FAQ>>.

=== What does Cassandra Source Connector provide that I cannot get with open-source Apache Pulsar?

The DataStax Cassandra Source Connector implements, in effect, the reverse of Apache Pulsar or DataStax Cassandra Sink Connector. With the CSC, the source takes data from Cassandra and puts that date onto a data topic. From there, the data can be published to external platforms like Snowflake, Elasticsearch, and so on.

=== Which Kubernetes platforms are supported by DataStax Cassandra Source Connector?

They include Minikube, K8d, Kind, Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service, Amazon Kubernetes Service (AKS), and other commonly used platforms. You can also deploy the CDC producer with the https://github.com/datastax/cass-operator[cass-operator].

[#gitHubRepos]
=== Where is the DataStax Cassandra Source Connector public GitHub repo?

The source for this FAQs document is co-located with the Cassandra Source Connector repo code, examples, and additional documentation: access the [repo here](https://github.com/datastax/cassandra-source-connector).

=== How do I install Cassandra Data Connector?

Download the tar file from the DataStax [Downloads site](https://downloads.datastax.com/#cdc). Then follow the xref:install.adoc[install] instructions. The tarball contains the Cassandra Data Connector distribution's NAR file.

=== What is Pulsar Heartbeat?

https://github.com/datastax/pulsar-heartbeat[Pulsar Heartbeat] monitors the availability, tracks the performance, and reports failures of the Pulsar cluster. It produces synthetic workloads to measure end-to-end message pubsub latency.  Pulsar Heartbeat is a cloud-native application that can be installed by Helm within the Pulsar Kubernetes cluster.

=== What is Prometheus?

https://prometheus.io/docs/introduction/overview/[Prometheus] is an open-source tool to collect metrics on a running app, providing real-time monitoring and alerts.

=== What is Grafana?

https://grafana.com/[Grafana] is a visualization tool that helps you make sense of metrics and related data coming from your apps via Prometheus, for example.
