= Installing DataStax Cassandra Data Connector 

Install DataStax Cassandra Data Connector from the DataStax distribution tar file using an account that has write access to the Pulsar configuration directory.

The supported operating systems are Linux and macOS.

== Supported Apache® Pulsar versions

Install the DataStax Apache® Pulsar Connector on Apache Pulsar 2.7.0 or later.

IMPORTANT: https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
By downloading this DataStax product, you agree to the terms of the open-source Apache-2.0 license agreement.

Perform the following steps on a Pulsar Connect node:

. Download the tar file from the https://downloads.datastax.com/#cdc[DataStax downloads site].
If you agree, enable the *Terms* checkbox and click the download icon.
. Extract the files:
+
[source,language-bash]
----
tar zxf cassandra-data-connector-0.1.0.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-data-connector-0.1.1`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
conf/example.yml
cassandra-data-connector-0.1.0.nar
----

. Create a `connectors` directory in the Pulsar home directory if it doesn't exist.
. Move the DataStax connector NAR to the Pulsar `connectors` directory:
+
[source,language-bash]
----
mv installation_location/cassandra-data-connector-0.1.0.nar pulsar_home/connectors
----

. Copy the sample example.yml configuration file from `cassandra-data-connector-0.1.0/conf/` to the Pulsar configuration directory, which is typically the `config` or `etc` directory.
. Update the settings as necessary.
+
IMPORTANT: If you are using the `cloud.secureConnectBundle`, *ALL* subproperties under `ssl:` must be empty.

. Ensure that the user running Pulsar has permission to access the configuration and NAR files.
