= Installing the DataStax CDC for Apache Cassandra

== Download the DataStax Cassandra Source Connector for Apache Pulsar

IMPORTANT: https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
By downloading this DataStax product, you agree to the terms of the open-source Apache-2.0 license agreement.

Perform the following steps:

. Download the *cassandra-source-connectors-<version>.tar* tar file from the https://github.com/datastax/cassandra-source-connector/releases[GitHub Releases page].

. Extract the files:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-<version>.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-<version>`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
agent-c3-luna-<version>-all.jar
agent-c4-luna-<version>-all.jar
pulsar-cassandra-source-<version>.nar
----

== Starting Cassandra with the CDC agent

All data nodes of your Cassandra datacenter must run the CDC JVM agent to send mutations into the events topic of your streaming software. Start your Cassandra nodes with the appropriate CDC agent binary matching your
Cassandra version (3.11 or 4.0) and your streaming platform (Apache Pulsar).

As a Java agent, the CDC agent parameters take place after the jar file name in the form of a comma separated list of paramName=paramValue. Here is an example for Apache Pulsar on Cassandra version 4.0 nodes:

[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/agent-c4-luna-<version>-all.jar=pulsarServiceUrl=pulsar://pulsar:6650"
----

== Producer Parameters

include::agentParams.adoc[]

== Deploy the Cassandra Source Connector

In order to deploy the Cassandra Source Connector NAR file in your Pulsar cluster, you can copy it into
the pulsar connectors directory or upload it. You have to specify the following parameters:

* The connector name- remember, you have one connector per replicated Cassandra table
* The destination topic for Cassandra data
* The xref:cfgCassandraSource.adoc[Cassandra Source connector configuration]

[source,language-bash]
----
pulsar-admin source localrun \
--archive /path/to/pulsar-cassandra-source-<version>.nar \
--tenant public \
--namespace default \
--name cassandra-source-1 \
--destination-topic-name data-ks1.table1 \
--source-config '{"contactPoints":"localhost:9042", "localDc":"datacenter1", "keyspace":"ks1", "table":"table1", "eventsTopicPrefix": "persistent://public/default/events-", "eventsSubscriptionName":"sub1", "keyConverter":"com.datastax.oss.pulsar.source.converters.AvroConverter","valueConverter":"com.datastax.oss.pulsar.source.converters.JsonConverter"}'
----

Then check your connector is properly running with no error:
[source,language-bash]
----
pulsar-admin source status --name cassandra-source-1
----

include::cfgCassandraSource.adoc[]

include::cfgCassandraAuth.adoc[]

include::cfgCassandraSSL.adoc[]

include::cfgCassandraJavaDriverSettings.adoc[]

== Scaling up your configuration

In order to increase the throughput of the CDC replication on multiple Pulsar brokers, you can configure https://pulsar.apache.org/docs/en/admin-api-topics/#manage-partitioned-topics[Pulsar partitioned topics] before starting the CDC agent. Depending on the desired latency, you can adjust the *pulsarBatchDelayInMs* to group messages.

You can also increase the Cassandra Source connector *batch.size*, and the *query.executors*, and adjust the memory cache settings, the cache size with *cache.max.capacity*, the entry retention duration *cache.expire.after.ms* and the number of MD5 digest per primary key entry with *cache.max.digest*.


