= Installing DataStax Cassandra Source Connector

== Download the Datastax Cassandra Source Connector

IMPORTANT: https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
By downloading this DataStax product, you agree to the terms of the open-source Apache-2.0 license agreement.

Perform the following steps on a Pulsar Connect node:

. Download the tar file from the https://downloads.datastax.com/#csc[DataStax downloads site].
If you agree, enable the *Terms* checkbox and click the download icon.
. Extract the files:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-0.1.0.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-0.1.0`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
producer-v3-kafka-0.1.0-SNAPSHOT-all.jar
producer-v3-pulsar-0.1.0-SNAPSHOT-all.jar
producer-v4-kafka-0.1.0-SNAPSHOT-all.jar
producer-v4-pulsar-0.1.0-SNAPSHOT-all.jar
source-kafka-0.1.0-SNAPSHOT-all.jar
source-pulsar-0.1.0-SNAPSHOT.nar
----

== Starting Cassandra with the producer agent.

All data node of your Cassandra datacenter must run the producer JVM agent to send mutations into the events topic of
your streaming software. Start your Cassandra nodes with the appropriate producer binary matching your
Cassandra version (3.11 or 4.0) and your streaming platform (Apache Pulsar or Kafka).

Example for Apache Kafka on Cassandra version 4.0 nodes:

[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v4-kafka-0.1-all.jar=kafkaBrokers=brockers:9092,kafkaRegistryUrl=http://schemaregistry:8081"
----

=== Producer configuration

The producer JVM agent takes the following settings:

[cols="1,1,1"]
|===
|Setting |Default |Description

|cdcRelocationDir
|$cassandra.storagedir/cdc_backup
|The location where Cassandra commitlog files are relocated.

|cdcPoolIntervalMs
|60000
|Watching timeout when watching for commitlog files on disk.

|errorCommitLogReprocessEnabled
|false
|When true, reprocessed errored commitlogs files located in the cdcRelocationDir.

|topicPrefix
|events-
|Prefix used to build the events topic name. The keyspace name dot the table name are appended to this prefix to build the topic name.

|pulsarServiceUrl
|pulsar://localhost:6650
|Pulsar service URL

|kafakaBrokers
|localhost:9092
|Kafka brokers address

|kafkaSchemaRegistryUrl
|http://localhost:8081
|Kafka registry URL
|===

== Deploy the Kafka Cassandra Source Connector

[source,language-bash]
----
pulsar-admin source localrun \
--archive /path/to/source-pulsar-<version>.nar \
--tenant public \
--namespace default \
--name cassandra-source-1 \
--destination-topic-name data-ks1.table1 \
--source-config '{"contactPoints":"localhost:9042", "localDc":"datacenter1", "keyspace":"ks1", "table":"table1", "eventsTopicPrefix": "persistent://public/default/events-", "eventsSubscriptionName":"sub1", "keyConverter":"com.datastax.oss.pulsar.source.converters.AvroConverter","valueConverter":"com.datastax.oss.pulsar.source.converters.JsonConverter"}'
----

== Deploy the Pulsar Cassandra Source Connector

[source,language-bash]
----
curl -XPOST -H "Content-Type: application/json" "http://localhost:8083/connectors" -d '{
"name": "cassandra-source-1",
  "config": {
    "connector.class": "com.datastax.oss.kafka.source.CassandraSourceConnector",
    "tasks.max": "1",
    "bootstrap.servers": "broker:29092",
    "schema.registry.url": "http://schema-registry:8081",
    "errors.log.enable": true,
    "errors.log.include.messages": true,
    "events.topic": "events-ks1.table1",
    "data.topic": "data-ks1.table1",
    "keyspace": "ks1",
    "table": "table1",
    "contactPoints": "host.docker.internal",
    "loadBalancing.localDc": "datacenter1",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url": "http://schema-registry:8081",
    "value.converter.schema.registry.url": "http://schema-registry:8081"
  }
}'
----
