= Installation Guide

== Download the Datastax Cassandra Source Connector

IMPORTANT: https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
By downloading this DataStax product, you agree to the terms of the open-source Apache-2.0 license agreement.

Perform the following steps on a Pulsar Connect node:

. Download the tar file from the https://downloads.datastax.com/#csc[DataStax downloads site].  If you agree, enable the *Terms* checkbox and click the download icon.
. Extract the files:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-<version>.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-<version>`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
producer-v3-pulsar-0.1.0-SNAPSHOT-all.jar
producer-v4-pulsar-0.1.0-SNAPSHOT-all.jar
source-pulsar-0.1.0-SNAPSHOT.nar
----

== Starting Cassandra with the producer agent.

Each data nodes of your Cassandra data center must run the producer JVM agent to send mutations into the events topic of your streaming software. Start your Cassandra nodes with the appropriate producer binary matching your Cassandra version (3.11 or 4.0) and your streaming platform, in this case Apache Pulsar.

As a Java agent, the CDC producer parameters take place after the jar file name in the form of a comma separated list of `paramName=paramValue`. The following example is for Apache Pulsar on Cassandra version 4.0 nodes with the Pulsar service available on host `schemaregistry`:

[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v4-pulsar-<version>-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----

== Deploy the Pulsar Cassandra Source Connector

To deploy the Cassandra Source Connector NAR file in your Pulsar cluster, you can copy it into the Pulsar connectors directory or upload it anywhere on the node and specify it. The following parameters are required:

* The connector name.  There must be one connector per replicated Cassandra table.
* The destination topic for Cassandra data.
* The connector configuration.  See xref:cfgCassandraConnection.adoc[].

[source,language-bash]
----
pulsar-admin source localrun \
--archive /path/to/source-pulsar-<version>.nar \
--tenant public \
--namespace default \
--name cassandra-source-1 \
--destination-topic-name data-ks1.table1 \
--source-config '{"contactPoints":"localhost:9042", "localDc":"datacenter1", "keyspace":"ks1", "table":"table1", "events.topic":"events-ks1.table1", "keyConverter":"com.datastax.oss.pulsar.source.converters.AvroConverter","valueConverter":"com.datastax.oss.pulsar.source.converters.JsonConverter"}'
----
