= Installing {cdc_cass} for VM deployment

== Download the DataStax Change Data Capture (CDC) Agent for Apache Cassandra(R)

[IMPORTANT]
====
By downloading this DataStax product, you agree to the terms of the open-source https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
====

Perform the following steps:

. Download the change agent tar file from the https://downloads.datastax.com/#cassandra-change-agent[DataStax downloads page]. +
The following files are available in the tar file:
+
[cols="1,1"]
|===
| Cassandra type | JAR file

| Apache Cassandra 3.x | agent-c3-<version>-all.jar
| Apache Cassandra 4.x | agent-c4-<version>-all.jar
| DSE 6.8.16+ | agent-dse4-<version>-all.jar

|===

. Extract the files from the tar with the following command:
+
[source,bash]
----
tar xvf cassandra-source-agents-<version>.tar
----

. Use the file that matches your Cassandra type and streaming platform.

== Start Cassandra with the Change Agent for Cassandra

All data nodes of your Cassandra or DSE datacenter must run the change agent as a JVM agent to send mutations into the events topic of your streaming software.
Start your Cassandra or DSE nodes with the appropriate producer binary matching your Cassandra (3.11 or 4.0) or DSE (6.8.16) version and your streaming platform: IBM Elite Support for Apache Pulsar (formerly DataStax Luna Streaming) 2.8+ or Apache Pulsar 2.8.1+.

In CDC agent versions *before 1.0.3*, the CDC agent Pulsar connection parameters were provided as extra JVM options after the `jar` file name in the form of a comma-separated list of `paramName=paramValue`, as below:

[source,bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/agent-c4-<version>-all.jar=pulsarServiceUrl=pulsar://pulsar:6650"
----

In CDC agent versions *after 1.0.3*, the CDC agent Pulsar connection parameters are also provided as system environment parameters in `cassandra-env.sh`. The same JVM option above is now appended to `cassandra-env.sh` as below:

[source,bash]
----
export CDC_PULSAR_SERVICE_URL="pulsar://<pulsar_server_ip>:6650"
----

And to enable CDC for your C* deployment:

[source,bash]
----
JVM_OPTS="$JVM_OPTS -javaagent:/home/automaton/cdc104/agent-dse4-pulsar-1.0.5-all.jar"
----

The CDC parameter mappings between JVM and C* environment variables are provided in xref:stringMappings.adoc[CDC Environment Parameter Strings]. +
For the full set of JVM configuration options, see xref:install.adoc#agentParams[].

== `Cassandra.yaml`
In addition to configuring the change agent, enable CDC on the Cassandra node by setting `cdc_enabled` to `true` in the `cassandra.yaml` file.

For Cassandra 4.X and DSE 6.8.16+, you can configure the commit log sync period.
This parameter controls how often the commit logs are made available for CDC processing.
The default is 10 seconds.
To reduce the latency from when the table is updated to when the event is available in the data topic, decrease the period, such as 2 seconds.

The total amount of CDC data stored is controlled by the `cdc_total_space_in_mb` parameter.
If the amount of unprocessed CDC reaches this threshold, writes to CDC enabled tables will be rejected.
Make sure you have the change agent installed on the node when CDC is enabled.
Without the change agent to process the CDC data, the space used will grow until it hits this limit and then writes to CDC-enabled tables will stop.

Here is an example set of configurations for the `cassandra.yaml` file:

[source,bash]
----
cdc_enabled: true
commitlog_sync_period_in_ms: 2000
cdc_total_space_in_mb: 50000
----

[#agentParams]
== Change Agent Parameters

include::partial$agentParams.adoc[]

== Download {cdc_pulsar}
IMPORTANT
====
By downloading this DataStax product, you agree to the terms of the open-source https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
====

. Download the `cassandra-source-connectors-<version>.tar` file from the https://downloads.datastax.com/#cassandra-source-connector[DataStax downloads page].

The following files are available:

[cols="1"]
|===
| Streaming platform |  NAR file

| Apache Pulsar and IBM Elite Support for Apache Pulsar (formerly DataStax Luna Streaming) 2.8 | pulsar-cassandra-source-<version>.nar

|===

Extract the files from the tar with the following command:

[source,bash]
----
tar xvf cassandra-source-connectors-<version>.tar
----

Use the version that matches your streaming platform.

== Deploy {cdc_pulsar}

To deploy the {cdc_pulsar} `NAR` file in your Pulsar cluster, upload it to your Pulsar cluster using the `pulsar-admin sources create` command.
You need to deploy {cdc_pulsar} for each CDC-enabled table.

For each CDC-enabled table, the change agent will send events to the events topic.
The topic name is determined by the `topicPrefix` setting in the agent (default is `events-`).
The `<keyspace_name>.<table_name>` is appended to the prefix to build the topic name.

You have to specify the following parameters:

* Connector name. You have one connector per CDC-enabled Cassandra table, make sure to use a unique name.
* Previously downloaded {cdc_pulsar} `NAR` file.
* Pulsar `tenant` and `namespace` where the connector will run.
* Destination `topic` for Cassandra data (`data` topic).
* Number of instances (parallelism) of the connector. For high-volume tables, you might need to run multiple connector instances to prevent a growing backlog on the events topic.
* Name of the `events` topic the connector will read from.
* Keyspace and table associated with the events topics.
* Connection information (such as contact points and DC information) for Cassandra.

Here is an example:

[source,bash]
----
pulsar-admin source create \
--name cassandra-source-1 \
--archive /path/to/pulsar-cassandra-source-<version>.nar \
--tenant public \
--namespace default \
--destination-topic-name public/default/data-ks1.table1 \
--parallelism 1 \
--source-config '{
    "events.topic": "persistent://public/default/events-cdc-ks1.table1",
    "keyspace": "ks1",
    "table": "table1",
    "contactPoints": "localhost",
    "port": 9042,
    "loadBalancing.localDc": "DC1",
    "auth.provider": "PLAIN",
    "auth.username": "<username>",
    "auth.password": "<password>"
}'
----

Then check your connector is in the running state with no errors:
[source,bash]
----
pulsar-admin source status --name cassandra-source-1
----

Once the connector is running, it will process events from the `events` topic and publish the result to the `data` topic.

For the full set of source configuration options, see xref:install.adoc#datastax-cassandra-source-connector-for-apache-pulsar-settings[{cdc_pulsar} settings].
For the full set of Cassandra authentication options, see xref:install.adoc#cassandra-authentication-settings[Cassandra Authentication settings].
For the full set of Cassandra SSL settings, see xref:install.adoc#cassandra-ssltls-settings[Cassandra SSL/TLS settings].
For advanced configuration of the Cassandra driver in the {cdc_pulsar}, see xref:install.adoc#pass-cdc-for-cassandra-settings-directly-to-the-datastax-java-driver[Pass {cdc_pulsar} settings directly to the DataStax Java driver].

== Enabling and disabling CDC on a table

Once the change agent is installed and the connector is running, you can enable or disable CDC on table using the following commands:

[source,bash]
----
CREATE TABLE foo (a int, b text, PRIMARY KEY(a)) WITH cdc=true;
ALTER TABLE foo WITH cdc=true;
ALTER TABLE foo WITH cdc=false;
----

When CDC is enabled on a table, updates to that table are sent by the change agent to the {cdc_pulsar} which further processes the event and then sends it to the data topic when it can be processed by other connectors (for example, Elasticsearch).

include::partial$cfgCassandraSource.adoc[]

include::partial$cfgCassandraAuth.adoc[]

include::partial$cfgCassandraSSL.adoc[]

== Pass {cdc_pulsar} settings directly to the DataStax Java driver

In your {cdc_pulsar} configuration file, you can directly pass settings to the DataStax Java driver by using the `datastax-java-driver` prefix.
For example:

[source,console]
----
datastax-java-driver.basic.request.consistency=ALL
----

== Mapping {cdc_pulsar} settings to Java driver properties

The following table identifies functionally equivalent {cdc_pulsar} and DataStax Java driver settings.

NOTE: If you define both in your configuration, the {cdc_pulsar} setting take precedence over the `datastax-java-driver.property-name`.
If you do not provide either in your configuration, {cdc_pulsar} defaults are in effect.

For information about the Java properties, refer to the link:https://docs.datastax.com/en/developer/java-driver-dse/2.3/manual/core/configuration/[DataStax Java driver documentation].

|===
| {csc_pulsar_first} | Using datastax-java-driver prefix

| `contactPoints`
| `datastax-java-driver.basic.contact-points`

| `loadBalancing.localDc`
| `datastax-java-driver.basic.load-balancing-policy.local-datacenter`

| `cloud.secureConnectBundle`
| `datastax-java-driver.basic.cloud.secure-connect-bundle`

| `queryExecutionTimeout`
| `datastax-java-driver.basic.request.timeout`

| `connectionPoolLocalSize`
| `datastax-java-driver.advanced.connection.pool.local.size`

| `compression`
| `datastax-java-driver.advanced.protocol.compression`

| `metricsHighestLatency`
| `datastax-java-driver.advanced.metrics.session.cql-requests.highest-latency`
|===

There is a difference between the {cdc_pulsar}'s `contactPoints` setting and the Java driver's `datastax-java-driver.basic.contact-points`.
For {cdc_pulsar}'s `contactPoints`, the value of the port is appended to every host provided by this setting.
For `datastax-java-driver.basic.contact-points`, you must provide the fully qualified contact points (`host:port`).

By passing in the Java driver's setting, this option gives you more configuration flexibility because you can specify a different port for each host. For example:

[source,console]
----
datastax-java-driver.basic.contact-points = 127.0.0.1:9042, 127.0.0.2:9042
----

=== Java driver reference

For more information, refer to the link:https://docs.datastax.com/en/developer/java-driver/4.3/manual/core/configuration/reference/[Java driver reference configuration] topic.

== Scaling up your configuration

If your connector is not keeping up and the messages in the events topic are growing, increase the number of connector instances using the `parallelism` parameter.
Pulsar ensures in-order processing using Key_Shared subscriptions.

If the volume of data in the events topic is very high, https://pulsar.apache.org/docs/en/admin-api-topics/#manage-partitioned-topics[partition] the events topic to distribute the load across multiple Pulsar brokers.
Do this before starting the change agent, since by default Pulsar will auto-create non-partitioned topics.
If you are using partitioned topics, change `events.subscription.type` to `Failover` to ensure in-order delivery when running multiple connector instances.

To further improve the throughput, you can adjust the `pulsarBatchDelayInMs` in the change agent to batch messages in the change agent before sending them to Pulsar.

To improve performance on individual connector instances as they read data from Cassandra, you can adjust the `batch.size` and the `query.executors`.
Increasing these values from their defaults will increase parallelism within the connector instances.

The de-duplication cache is configurable, including the cache size with `cache.max.capacity`, the entry retention duration `cache.expire.after.ms` and the number of MD5 digest per primary key entry with `cache.max.digest`.
