= Installing DataStax Cassandra Source Connector

Organizations who want to implement Change Data Capture (CDC) from their https://cassandra.apache.org/index.html[Apache Cassandra] cluster can use the https://github.com/datastax/cassandra-source-connector/tree/master[DataStax Cassandra&reg; Source Connector (CSC)] to capture change data events into https://pulsar.apache.org[Apache Pulsar].

For more information on how the CSC works, see the xref:index.adoc[] page.

This guide allows you to set up the CSC with the fewest possible steps.  For more configuration options, see the **References** section.  


== Prerequisites

* Apache Cassandra 3.11 or 4.0

== Step 0: Download the Cassandra Source Connector

[IMPORTANT]
====
By downloading this DataStax product, you agree to the terms of the link:https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
====

. Go to the download page at https://downloads.datastax.com/#csc[DataStax downloads site].
. Select **Tools**, then **DataStax Cassandra Source Connector**. 
. Agree to the Terms and Conditions and **Download** the CSC.
. Extract the files:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-<version>.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-<version>`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
producer-v3-pulsar-<version>-SNAPSHOT-all.jar
producer-v4-pulsar-<version>-SNAPSHOT-all.jar
source-pulsar-<version>-SNAPSHOT.nar
----

== Step 1: Install the Cassandra CDC Producer

=== Install the Cassandra CDC Producer

To install the Cassandra CDC Producer, follow these steps:

. Copy the appropriate Cassandra Producer binary based on your version of Cassandra to each Cassandra node:
+
[cols=2*,options=header]
|===
|Cassandra Version
|CDC Pulsar Producer

|3.11 
|producer-v3-pulsar-<version>-SNAPSHOT-all.jar
|4.0 
|producer-v4-pulsar-<version>-SNAPSHOT-all.jar
|===
+
. Restart each Cassandra node and specify the Producer parameters in the `JVM_EXTRA_OPTS` setting, with each parameter as a comma-separated list in the `parameter=value` format.
+
In this example, the required `pulsarServiceUrl` is included. 
This setting points the Cassandra CDC Producer at the Pulser service. 
In this case, the host name of the Pulsar service is `schemaregistry` using **Broker data port** `6650`. 
For more, see link:producerParams.adoc[Producer Parameters]. 
+
[cols="2,2a",options=header]
|===
|Cassandra Version
|CDC Pulsar Producer

|3.11 
|[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v3-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----

| 4.0 
| [source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v4-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----
|===

== Step 2: Install Pulsar

Install Apache Pulsar using the https://pulsar.apache.org/docs/en/standalone/[installation instructions] for local, Docker, or Kubernetes installation.

[NOTE]
====
Alternatively, you can install DataStax Luna Streaming for a production-level, secure distribution of Apache Pulsar.  For instructions on how to install Luna Streaming, see the instructions for your environment:

* https://docs.datastax.com/en/luna/streaming/2.7/quickstart-helm-installs.html[Quick Start for Helm Chart installs]
* https://docs.datastax.com/en/luna/streaming/2.7/quickstart-server-installs.html[Quick Start for Server/VM installs]
====

== Step 3: Install the Pulsar Cassandra Source Connector

Install the Pulsar Cassandra Source Connector and set up the topics to capture Cassandra CDC events.

. Set the `tenant` and `namespace` for the topics to store the Cassandra CDC events. For this example, the tenant is `cassandra` with the namespace `csc`:

+
[source,language-bash]
----
pulsar-admin tenants create cassandra
pulsar-admin namespace create cassandra/csc
----

+
**Optional:** Use the `set-auto-topic-creation <tenant>/<namespace> --enable` setting to auto-create topics for the specified namespace:

+
[source,language-bash]
----
pulsar-admin --admin-url $PULSAR_BROKER_HTTP $PULSAR_ADMIN_AUTH namespaces set-auto-topic-creation cassandra/csc --enable
----

+
[NOTE]
====
Alternatively, create the topics manually. For more, see https://pulsar.apache.org/docs/en/admin-api-topics[Manage topics].
====

+
. Add the Source Connector file `source-pulsar-<version>-SNAPSHOT.nar` to your Pulsar service using one of the following:

+
* Use a default Connector directory for your Pulsar server.
For more information, see https://pulsar.apache.org/docs/en/io-use/#configure-a-default-storage-location-for-a-connector[Configure a default storage location for a connector]. By default, this creates `./connectors` in the Pulsar root directory.
* Upload the Source Connector file anywhere on the Pulsar server, noting the exact filepath.
+
. Add the Source Connector details.

+
There is a Source Connector configuration for each Cassandra table. You can the `pulsar-admin` option to run the connector locally or install the connector with the appropriate YAML configuration file. Both options require the following information:

+
* `tenant` and `namespace`: Where the CDC events from the Cassandra table are stored.
* `name`: Because each Cassandra table requires a Source Connector setting, the `name` of the Source Connector must be unique.
* `destination-topic-name`: Location for the final Cassandra table CDC data formatted as `data-{cassandra-keyname}.{table-name}`.
* `source-config`: JSON format that sets the following parameters:
** `contactPoints`: The Cassandra CQL native port from which to receive Cassandra submissions.
** `localDc`: The datacenter used for load balancing.
** `keyspace`:  The Cassandra keyspace.
** `table`: The table for which CDC data is being captured.
** `events.topic`: Where the Cassandra CDC data will initially be before verification and de-duplication. The format should be `events-{cassandra-keyname}.{table-name}`.
** `keyConverter` and `valueConverter`:  Specifies the Pulsar converters used to convert Cassandra keys and JSON data into Pulsar format.

=== Examples

The following settings are used in these examples:

* `cluster_name`: 'Documentation'
* `key`: `cycling`
* `table`: `cyclist_name`
* `tenant`: `cassandra`
* `namespace`: `csc`

==== pulsar-admin local run

If running `pulsar-admin` from the command line, use the following example, replacing `<version>` with the version of the `.nar` file used.

[source,language-bash]
----
pulsar-admin source localrun \
--archive ./connector/source-pulsar-<version>.nar \
--tenant cassandra \
--namespace csc \
--name cassandra-cycling-cyclist-name \
--destination-topic-name data-cycling.cyclist_name \
--source-config '{"contactPoints":"[localhost]", "loadBalancing.localDc":"datacenter1", "port":"9042", "keyspace":"cycling", "table":"cyclist_name", "events.topic":"events-cycling.cyclist_name", "key.converter":"com.datastax.oss.pulsar.source.converters.AvroConverter","value.converter":"com.datastax.oss.pulsar.source.converters.JsonConverter"}'
----

==== Install connector with YAML file

To run the Cassandra Source Connector from within your Pulsar server, use the YAML file to set the parameters.  For more information, see http://pulsar.apache.org/docs/en/io-use/#configure-a-connector-with-a-yaml-file[How to use Pulsar connectors].

For each Cassandra table to capture the CDC data on, a separate YAML file will be specified.  It is recommended to name them `SouceConnector-{Cassandra Table}.yml`, replacing `{Cassandra Table}` with the name of the table to be captured.

. Store the Source Connector `.nab` file in the `./connectors` directory of the Pulsar server.
. Verify the `./conf/functions_worker.yml` file has the `connectorsDirectory` option set. By default, `connectorsDirectory: ./connectors`.
+
The following example would be stored in the Pulsar servers `conf` directory as `SourceConnector-cyclist_name.yml`:
+
[source,language-yaml]
----
tenant: cassandra
namespace: csc
name: cassandra-cycling-cyclist-name
destination-topic-name: data-cycling.cyclist_name
configs:
  contactPoints: [localhost]
  loadBalancing.localDc: datacenter1
  port: 9042
  keyspace: cycling
  table: cyclist_name
  events.topic: events-cycling.cyclist_name
  key.converter: com.datastax.oss.pulsar.source.converters.AvroConverter
  value.converter: com.datastax.oss.pulsar.source.converters.JsonConverter
----
+
. Install the Source Connector with the following `pulsar-admin` command:
+
[source,language-bash]
----
pulsar-admin source create -a ./connector/source-pulsar-<version>.nar  \
    --source-config-file ./conf/SourceConnector-cyclist_name.yml
----

== Read the Cassandra data

To read the gathered data from the Cassandra cluster, create a Pulsar Consumer directed at the specified `destination-topic-name`. For more information, see https://pulsar.apache.org/docs/en/concepts-messaging/#consumers[Messaging].
