= Installing the DataStax Cassandra Source Connector

== Download the Datastax Cassandra Source Connector

IMPORTANT: https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
By downloading this DataStax product, you agree to the terms of the open-source Apache-2.0 license agreement.

Perform the following steps on a Pulsar Connect node:

. Download the tar file from the https://downloads.datastax.com/#csc[DataStax downloads site].
If you agree, enable the *Terms* checkbox and click the download icon.
. Extract the files:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-<version>.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-<version>`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
producer-v3-pulsar-<version>-SNAPSHOT-all.jar
producer-v4-pulsar-<version>-SNAPSHOT-all.jar
pulsar-cassandra-source-<version>-SNAPSHOT.nar
----

== Starting Cassandra with the producer agent

All data nodes of your Cassandra datacenter must run the producer JVM agent to send mutations into the events topic of your streaming software. Start your Cassandra nodes with the appropriate producer binary matching your
Cassandra version (3.11 or 4.0) and your streaming platform (Apache Pulsar).

As a Java agent, the CDC producer parameters take place after the jar file name in the form of a comma separated list of paramName=paramValue. Here is an example for Apache Pulsar on Cassandra version 4.0 nodes:

[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v4-pulsar-<version>-all.jar=pulsarServiceUrl=pulsar://pulsar:6650"
----

== Producer Parameters

include::producerParams.adoc[]

== Deploy the Kafka Cassandra Source Connector

In order to deploy the Cassandra Source Connector NAR file in your Pulsar cluster, you can copy it into
the pulsar connectors directory or upload it. You have to specify the following parameters:

* The connector name- remember, you have one connector per replicated Cassandra table
* The destination topic for Cassandra data
* The xref:cfgCassandraSource.adoc[Cassandra Source connector configuration]

[source,language-bash]
----
pulsar-admin source localrun \
--archive /path/to/pulsar-cassandra-source-<version>.nar \
--tenant public \
--namespace default \
--name cassandra-source-1 \
--destination-topic-name data-ks1.table1 \
--source-config '{"contactPoints":"localhost:9042", "localDc":"datacenter1", "keyspace":"ks1", "table":"table1", "eventsTopicPrefix": "persistent://public/default/events-", "eventsSubscriptionName":"sub1", "keyConverter":"com.datastax.oss.pulsar.source.converters.AvroConverter","valueConverter":"com.datastax.oss.pulsar.source.converters.JsonConverter"}'
----

Then check your connector is properly running with no error:
[source,language-bash]
----
pulsar-admin source status --name cassandra-source-1
----

== Monitoring and Alerting System

The producer agent exposes metrics with https://docs.datastax.com/en/landing_page/doc/landing_page/metricsandalerts.html[JMX], a technology within Java that provides tools for managing and monitoring applications. 
* https://docs.datastax.com/en/opscenter/6.8/[DSE Ops Center] can collect these exposed metrics for visualization and alerts, and pass them on to https://docs.datastax.com/en/monitoring/doc/monitoring/opsUseMetricsCollector.html[DSE Metrics Collector] for additional integration with Prometheus and Grafana.
* The https://github.com/datastax/metric-collector-for-apache-cassandra[Metrics Collector for Apache Cassandra] with Prometheus and Grafana dashboards provides the same functionality as DSE Metrics Collector, built on the well-supported collectd agent.
* Other monitoring tools like https://github.com/prometheus/jmx_exporter[JMX Exporter] by Prometheus are available, but may require additional tuning.

include::cfgCassandraSource.adoc[]

include::cfgCassandraAuth.adoc[]

include::cfgCassandraSSL.adoc[]

include::cfgCassandraJavaDriverSettings.adoc[]
