= Install and configure {cdc_cass}

This guide explains how to install and configure {cdc_cass_first} for the first time on your {cass} or {dse-short} cluster and Pulsar cluster.

[TIP]
====
For a shorter version of this guide, see xref:ROOT:cdcExample.adoc[].
====

== Prerequisites

The minimum requirements are as follows:

* Near real-time event streaming CDC requires {cass-short} version 3.11 or later, {cass-short} 4.0 or later, or {dse-short} 6.8.16 or later.
* Batch CDC only requires {cass-short} version 3.0 to 3.10.
* IBM Elite Support for Apache Pulsar (formerly {company} Luna Streaming) or Apache Pulsar 2.8.1 or later.
* Additional memory and CPU available on all {cass-short} nodes.

[NOTE]
====
{cass-short} has supported batch CDC since {cass-short} 3.0.
However, for near real-time event streaming, you must run at least {cass-short} 3.11 or {dse-short} 6.8.16.
====

Depending on the workloads of the CDC enabled {cass-short} tables, you might need to increase the CPU and memory specification of the {cass-short} nodes.

== Install {cdc_cass} for VM deployment

. Download the `cassandra-source-agents` tar file from the https://github.com/datastax/cdc-apache-cassandra/releases[{cdc_cass} GitHub repository].
The following files are available in the tar file:
+
[cols="1,1"]
|===
| {cass-short} type | JAR file

| {cass} 3.x | `agent-c3-**VERSION**-all.jar`
| {cass} 4.x | `agent-c4-**VERSION**-all.jar`
| {dse-short} 6.8.16 or later | `agent-dse4-**VERSION**-all.jar`

|===

. Extract the files from the tar with the following command:
+
[source,bash,subs="+quotes"]
----
tar xvf cassandra-source-agents-**VERSION**.tar
----

. Use the file that matches your {cass-short} type and streaming platform.

== Start {cass-short} with the {cdc-agent}

All data nodes of your {cass-short} or {dse-short} datacenter must run the change agent as a JVM agent to send mutations into the events topic of your streaming software.
Start your {cass-short} or {dse-short} nodes with the appropriate producer binary matching your {cass-short} (3.11 or 4.0) or {dse-short} (6.8.16) version and your streaming platform: IBM Elite Support for Apache Pulsar (formerly {company} Luna Streaming) 2.8+ or Apache Pulsar 2.8.1+.

In {cdc_agent} versions *before 1.0.3*, the {cdc_agent} Pulsar connection parameters were provided as extra JVM options after the `jar` file name in the form of a comma-separated list of `paramName=paramValue`, as below:

[source,bash,subs="+quotes"]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/agent-c4-**VERSION**-all.jar=pulsarServiceUrl=pulsar://pulsar:6650"
----

In {cdc_agent} versions *after 1.0.3*, the {cdc_agent} Pulsar connection parameters are also provided as system environment parameters in `cassandra-env.sh`. The same JVM option above is now appended to `cassandra-env.sh` as below:

[source,bash,subs="+quotes"]
----
export CDC_PULSAR_SERVICE_URL="pulsar://**PULSAR_SERVER_IP**:6650"
----

And to enable CDC for your {cass-short} deployment:

[source,bash]
----
JVM_OPTS="$JVM_OPTS -javaagent:/home/automaton/cdc104/agent-dse4-pulsar-1.0.5-all.jar"
----

The CDC parameter mappings between JVM and {cass-short} environment variables are provided in xref:stringMappings.adoc[CDC Environment Parameter Strings].

For the full set of JVM configuration options, see xref:install.adoc#agentParams[].

== cassandra.yaml

In addition to configuring the change agent, enable CDC on the {cass-short} node by setting `cdc_enabled` to `true` in the `cassandra.yaml` file.

For {cass-short} 4.x and {dse-short} 6.8.16 and later, you can configure the commit log sync period.
This parameter controls how often the commit logs are made available for CDC processing.
The default is 10 seconds.
To reduce the latency from when the table is updated to when the event is available in the data topic, decrease the period, such as 2 seconds.

The total amount of CDC data stored is controlled by the `cdc_total_space_in_mb` parameter.
If the amount of unprocessed CDC reaches this threshold, writes to CDC enabled tables are rejected.
Make sure you have the change agent installed on the node when CDC is enabled.
Without the change agent to process the CDC data, the space used grows until it hits this limit, and then writes to CDC-enabled tables stop.

Here is an example set of configurations for the `cassandra.yaml` file:

[source,bash]
----
cdc_enabled: true
commitlog_sync_period_in_ms: 2000
cdc_total_space_in_mb: 50000
----

[#agentParams]
== Change Agent Parameters

include::ROOT:partial$agentParams.adoc[]

== Download the {csc_pulsar_first}

Download the `cassandra-source-connectors` tar file from the https://github.com/datastax/cdc-apache-cassandra/releases[{cdc_cass} GitHub repository].

For Apache Pulsar and IBM Elite Support for Apache Pulsar (formerly {company} Luna Streaming) 2.8, the `pulsar-cassandra-source-<version>.nar` file is available.

Extract the files from the tar, specifying the version that matches your streaming platform:

[source,bash,subs="+quotes"]
----
tar xvf cassandra-source-connectors-**VERSION**.tar
----

== Deploy the {csc_pulsar}

To deploy the {csc_pulsar} `NAR` file in your Pulsar cluster, upload it to your Pulsar cluster using the `pulsar-admin sources create` command.
You need to deploy {csc_pulsar} for each CDC-enabled table.

For each CDC-enabled table, the change agent sends events to the events topic.
The topic name is determined by the `topicPrefix` setting in the agent (default is `events-`).
The `<keyspace_name>.<table_name>` is appended to the prefix to build the topic name.

You have to specify the following parameters:

* Connector name. You have one connector per CDC-enabled {cass-short} table, make sure to use a unique name.
* Previously downloaded {csc_pulsar} `NAR` file.
* Pulsar `tenant` and `namespace` where the connector will run.
* Destination `topic` for {cass-short} data (`data` topic).
* Number of instances (parallelism) of the connector. For high-volume tables, you might need to run multiple connector instances to prevent a growing backlog on the events topic.
* Name of the `events` topic the connector will read from.
* Keyspace and table associated with the events topics.
* Connection information (such as contact points and DC information) for {cass-short}.

Here is an example:

[source,bash,subs="+quotes"]
----
pulsar-admin source create \
--name cassandra-source-1 \
--archive /path/to/pulsar-cassandra-source-**VERSION**.nar \
--tenant public \
--namespace default \
--destination-topic-name public/default/data-ks1.table1 \
--parallelism 1 \
--source-config '{
    "events.topic": "persistent://public/default/events-ks1.table1",
    "keyspace": "ks1",
    "table": "table1",
    "contactPoints": "localhost",
    "port": 9042,
    "loadBalancing.localDc": "DC1",
    "auth.provider": "PLAIN",
    "auth.username": "**USERNAME**",
    "auth.password": "**PASSWORD**"
}'
----

Then check your connector is in the running state with no errors:
[source,bash]
----
pulsar-admin source status --name cassandra-source-1
----

Once the connector is running, it processes events from the `events` topic, and then publishes the result to the `data` topic.

For mre information and options, see the following:

* xref:install.adoc#datastax-cassandra-source-connector-for-apache-pulsar-settings[{csc_pulsar} settings]
* xref:install.adoc#cassandra-authentication-settings[{cass-short} Authentication settings]
* xref:install.adoc#cassandra-ssltls-settings[{cass-short} SSL/TLS settings]
* xref:install.adoc#pass-cdc-for-cassandra-settings-directly-to-the-datastax-java-driver[Pass {csc_pulsar} settings directly to the {company} Java driver]

== Enabling and disabling CDC on a table

Once the change agent is installed and the connector is running, you can enable or disable CDC on table using the following commands:

[source,bash]
----
CREATE TABLE foo (a int, b text, PRIMARY KEY(a)) WITH cdc=true;
ALTER TABLE foo WITH cdc=true;
ALTER TABLE foo WITH cdc=false;
----

When CDC is enabled on a table, updates to that table are sent by the change agent to the {csc_pulsar} which further processes the event and then sends it to the data topic when it can be processed by other connectors (for example, Elasticsearch).

include::partial$cfgCassandraSource.adoc[]

include::partial$cfgCassandraAuth.adoc[]

include::partial$cfgCassandraSSL.adoc[]

== Pass {csc_pulsar} settings directly to the {company} Java driver

In your {csc_pulsar} configuration file, you can directly pass settings to the {company} Java driver by using the `datastax-java-driver` prefix.
For example:

[source,console]
----
datastax-java-driver.basic.request.consistency=ALL
----

== Mapping {csc_pulsar} settings to Java driver properties

The following table identifies settings that are functionally equivalent between the {csc_pulsar} and the {company} Java driver.

NOTE: If you define both in your configuration, the {csc_pulsar} setting take precedence over the `datastax-java-driver.property-name`.
If you don't provide either in your configuration, {csc_pulsar} defaults are applied.

For information about the Java properties, refer to the https://docs.datastax.com/en/developer/java-driver/4.3/manual/core/configuration/reference/index.html[{company} Java driver documentation].

|===
| {csc_pulsar_first} | Using datastax-java-driver prefix

| `contactPoints`
| `datastax-java-driver.basic.contact-points`

| `loadBalancing.localDc`
| `datastax-java-driver.basic.load-balancing-policy.local-datacenter`

| `cloud.secureConnectBundle`
| `datastax-java-driver.basic.cloud.secure-connect-bundle`

| `queryExecutionTimeout`
| `datastax-java-driver.basic.request.timeout`

| `connectionPoolLocalSize`
| `datastax-java-driver.advanced.connection.pool.local.size`

| `compression`
| `datastax-java-driver.advanced.protocol.compression`

| `metricsHighestLatency`
| `datastax-java-driver.advanced.metrics.session.cql-requests.highest-latency`
|===

There is a difference between the {csc_pulsar}'s `contactPoints` setting and the Java driver's `datastax-java-driver.basic.contact-points`.
For {csc_pulsar}'s `contactPoints`, the value of the port is appended to every host provided by this setting.
For `datastax-java-driver.basic.contact-points`, you must provide the fully qualified contact points (`host:port`).

By passing in the Java driver's setting, this option gives you more configuration flexibility because you can specify a different port for each host. For example:

[source,console]
----
datastax-java-driver.basic.contact-points = 127.0.0.1:9042, 127.0.0.2:9042
----

=== Java driver reference

For more information, refer to the https://docs.datastax.com/en/developer/java-driver/4.3/manual/core/configuration/reference/index.html[Java driver reference configuration] topic.

== Scaling up your configuration

If your connector isn't keeping up and the messages in the events topic are growing, increase the number of connector instances using the `parallelism` parameter.
Pulsar ensures in-order processing using Key_Shared subscriptions.

If the volume of data in the events topic is very high, https://pulsar.apache.org/docs/en/admin-api-topics/#manage-partitioned-topics[partition] the events topic to distribute the load across multiple Pulsar brokers.
Do this before starting the change agent because Pulsar auto-creates non-partitioned topics by default.
If you are using partitioned topics, change `events.subscription.type` to `Failover` to ensure in-order delivery when running multiple connector instances.

To further improve the throughput, you can adjust the `pulsarBatchDelayInMs` in the change agent to batch messages in the change agent before sending them to Pulsar.

To improve performance on individual connector instances as they read data from {cass-short}, you can adjust the `batch.size` and the `query.executors`.
Increasing these values from their defaults increases parallelism within the connector instances.

The de-duplication cache is configurable, including the cache size with `cache.max.capacity`, the entry retention duration `cache.expire.after.ms` and the number of MD5 digest per primary key entry with `cache.max.digest`.
