= Monitor DataStax Cassandra Source Connector

== Producer Metrics

The CDC producer JVM agent running in Cassandra nodes provides a dedicated MBean type=*CdcProducer* with the following metrics:

[cols="2,1,3"]
|===
|Metric |Type |Description

|sentMutations
|Counter
|Number of Cassandra mutations successfully sent to the streaming platform.

|sentErrors
|Counter
|Number of errors when sending mutations to the streaming platform.

|commitLogReadErrors
|Counter
|Number of unrecoverable commitlog file reads.

|skippedMutations
|Counter
|Number of ignored mutations because the primary key has an unsupported column type.

|executedTasks
|Counter
|Number of executed task to process commitlog files.

|submittedTasksGauge
|Gauge
|Number of submitted tasks to the task dedicated thread pool.

|maxSubmittedTasks
|Gauge
|The maximum number of submitted tasks.

|pendingTasks
|Gauge
|Number of pending tasks to re-process a commitlog file.

|maxPendingTasks
|Gauge
|The maximum number of pending tasks.

|uncleanedTasks
|Gauge
|Number of tasks for which processed commitlog file have not yet been removed from the cdc_raw directory.

|maxUncleanedTasks
|Gauge
|The maximum number of uncleaned tasks.
|===

== Source Connector metrics

The Cassandra Source Connector also publish per message metrics:
[cols="2,1,3"]
|===
|Metric |Description

|cache_use
|1 when hitting the mutation cache, 0 otherwise.

|query_latency
|The CQL query latency in milliseconds to fetch the updated row. This is 0 when hitting the memory cache.
|===

Here an example of those user-defined metrics aggregated by pulsar when processing 2000 mutations:

[source,bash]
----
$ curl http://localhost:8080/metrics/ 2>/dev/null | grep user_metric
# HELP pulsar_source_user_metric_ User defined metric.
# TYPE pulsar_source_user_metric_ summary
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="cache_hit",quantile="0.5",} 1.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="cache_hit",quantile="0.9",} 1.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="cache_hit",quantile="0.99",} 1.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="cache_hit",quantile="0.999",} 1.0
pulsar_source_user_metric__count{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="cache_hit",} 2000.0
pulsar_source_user_metric__sum{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="cache_hit",} 1000.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="query_latency",quantile="0.5",} 6.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="query_latency",quantile="0.9",} 32.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="query_latency",quantile="0.99",} 395.0
pulsar_source_user_metric_{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="query_latency",quantile="0.999",} 509.0
pulsar_source_user_metric__count{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="query_latency",} 2000.0
pulsar_source_user_metric__sum{tenant="public",namespace="public/default",name="data-table1",instance_id="0",cluster="standalone",fqfn="public/default/data-table1",metric="query_latency",} 26068.0
----
