= DataStax Cassandra Source Connector Quick Start Guide

Users who want to implement CDC (Change Data Capture) from their https://cassandra.apache.org/index.html[Apache Cassandra] cluster can use the https://github.com/datastax/cassandra-source-connector/tree/master[DataStax Cassandra Source Connector (CSC)] to capture change data events into https://pulsar.apache.org[Apache Pulsar].

For more information on how the CSC works, see the link:index.adoc[About] page.

This guide instructions users setting up the CSC in the minimum number of steps.  The general outline of these steps are:

* Step 0: Download the CSC.
* Step 1: Install the CSC Cassandra Node.
* Step 2. Install Pulsar.
* Step 3: Configure Pulsar for Cassandra Event Topics and Data Topics.
* Step 4: Install the Source Connector.
* Step 5: Read the Data Topics from Apache Pulsar.

== Prerequisites

* Apache Cassandra 3.11 or 4.0

== Step 0: Download the CSC

. Go to the download page at https://downloads.datastax.com/#csc[DataStax downloads site].
. Select **Tools**, then **DataStax Cassandra Source Connector**. 
. Agree to the Terms and Conditions by enabling the Terms checkbox, then selecting **Download**.
. Extract the files with the following command:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-<version>.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-<version>`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
producer-v3-pulsar-<version>-SNAPSHOT-all.jar
producer-v4-pulsar-<version>-SNAPSHOT-all.jar
source-pulsar-<version>-SNAPSHOT.nar
----

== Step 1: Install the CSC

To install the Cassandra CDC Producer, follow these steps:

1. For each download the appropriate Cassandra Producer binary based on your version of Cassandra to each Cassandra node:

[cols=2*,options=header]
|===
|Cassandra Version
|CDC Pulsar Producer

|3.11 
|producer-v3-pulsar-<version>-SNAPSHOT-all.jar
|4.0 
|producer-v4-pulsar-<version>-SNAPSHOT-all.jar
|===

1. Restart Cassandra and specify the Producer parameters in the `JVM_EXTRA_OPTS` setting, which each parameter .  For more information on the producer parameters, see link:producerParams.adoc[Producer Parameters].  The following are examples of the Cassandra Producer parameters depending on your Cassandra version:

[cols="2,2a",options=header]
|===
|Cassandra Version
|CDC Pulsar Producer

|3.11 
|[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v3-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----

| 4.0 
| [source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v4-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----
|===

== Step 2: Install Pulsar

Depending on your organizations needs, there are different distributions of Apache Pulsar to use.  One is the official Apache Pulsar.  For high availability production systems, another option is Luna Streaming, based on Apache Pulsar and engineered to run on Kubernetes.

=== Install Apache Pulsar

Apache Pulsar has provided installation instructions for local, Docker, and Kubernetes based installations.  These are available on the https://pulsar.apache.org/docs/en/standalone/[Pulsar Documentation site].

=== Install Luna Streaming

The DataStax Luna Streaming service provides a production level, secure distribution of Apache Pulsar.  For instructions on how to install Luna Streaming, see either of the following based on your environment:

* https://docs.datastax.com/en/luna/streaming/2.7/quickstart-helm-installs.html[Quick Start for Helm Chart installs]
* https://docs.datastax.com/en/luna/streaming/2.7/quickstart-server-installs.html[Quick Start for Server/VM installs]

== Step 3: Configure Pulsar for Cassandra Event Topics and Data Topics

The CSC requires two topics for each Cassandra table that export the CDC data:

* Events:  This tracks the CDC events for each node that updates the table we are capturing CDC data for.
* Data:  The final version that removes duplications, and will be used by consumers to synchronize the CDC events to other services.

For more information on Pulsar topics, see the Pulsar documentation page https://pulsar.apache.org/docs/en/admin-api-topics/[Manage topics].

The following examples show how to create the topics for your CSC environment using `pulsar-admin`, the Pulsar command line client.  For this example, we will be capturing the CDC data for the table `cycling`

. Create the Pulsar **tenant** `cassandra` with `pulsar-admin tenants create cassandra`.
. Create the Pulsar **namespace** `csc` with `pulsar-admin namespaces create cassandra/csc`.
. Create the Pulsar **topics** that will be used for CDC capture with the following:
|[source,language-bash]
----
bin/pulsar-admin topics create persistent:cassandra/csc/cycling-events
bin/pulsar-admin topics create persistent:cassandra/csc/cycling-data
----
. Verify the topics have been created by listing them:
----
pulsar-admin list cassandra/csc
"persistent://cassandra/csc/cycling-events"
"persistent://cassandra/csc/cycling-data"
----

== Step 4: Install the Source Connector

To install the Pulsar Source Connector:

. Add the Source Connector file `source-pulsar-0.1.0-SNAPSHOT.nar` to your Pulsar service by one of two methods:
.. Use a default Connector directory for your Pulsar server.  For more information, see the Apache Pulsar documentation article  https://pulsar.apache.org/docs/en/io-use/#configure-a-default-storage-location-for-a-connector[Configure a default storage location for a connector].
.. Upload the Source Connector file anywhere on the Pulsar server.  Note the exact path of the file.
. Start Pulsar with the following options.  The most important of these are the following:
.. The Connector Name.  There will be one Connector per replicated Cassandra table.
.. The Destination Topic for the Cassandra Data.
.. The Connector Configuration including:???

For example, if we have the following:

NOTE:  I will likely rename these to be more reader-friendly.

* Connector Name: cassandra-source-1
* Destination Topic: data-ks1.table1
* Connector Configuration Settings:
** (Get the list here)

Then this will be used to launch the Pulsar server with the Source Connector enabled:

|[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v3-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----

== Step 5: Read the Cassandra Data

To read from the gathered data from the Cassandra cluster, create a Pulsar Consumer directed at the specific Destination Topic detailed above.  For more information, see the https://pulsar.apache.org/docs/en/concepts-messaging/#consumers[Apache Pulsar Consumer guide].