= Quick Start Guide

Organizations who want to implement CDC (Change Data Capture) from their https://cassandra.apache.org/index.html[Apache Cassandra] cluster can use the https://github.com/datastax/cassandra-source-connector/tree/master[DataStax Cassandra&reg; Source Connector (CSC)] to capture change data events into https://pulsar.apache.org[Apache Pulsar].

For more information on how the CSC works, see the link:index.adoc[About] page.

This guide instructions users setting up the CSC in the minimum number of steps.  The general outline of these steps are:

* Step 0: Download the CSC.
* Step 1: Install the Cassandra CDC Producer.
* Step 2. Install Pulsar.
* Step 3: Install the Pulsar CSC Source Connector.
* Step 4: Configure the Cassandra CDC Producer
* Step 5: Read the Data Topics from Apache Pulsar.

== Prerequisites

* Apache Cassandra 3.11 or 4.0

== Step 0: Download the CSC

. Go to the download page at https://downloads.datastax.com/#csc[DataStax downloads site].
. Select **Tools**, then **DataStax Cassandra Source Connector**. 
. Agree to the Terms and Conditions by enabling the Terms checkbox, then selecting **Download**.
. Extract the files with the following command:
+
[source,language-bash]
----
tar zxf cassandra-source-connector-<version>.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-source-connector-<version>`:
+
[source,no-highlight]
----
LICENSE
README.md
THIRD-PARTY.txt
producer-v3-pulsar-<version>-SNAPSHOT-all.jar
producer-v4-pulsar-<version>-SNAPSHOT-all.jar
source-pulsar-<version>-SNAPSHOT.nar
----

== Step 1: Install the Cassandra CDC Producer

=== Install the Cassandra CDC Producer

To install the Cassandra CDC Producer, follow these steps:

. Copy the appropriate Cassandra Producer binary based on your version of Cassandra to each Cassandra node:
+
[cols=2*,options=header]
|===
|Cassandra Version
|CDC Pulsar Producer

|3.11 
|producer-v3-pulsar-<version>-SNAPSHOT-all.jar
|4.0 
|producer-v4-pulsar-<version>-SNAPSHOT-all.jar
|===
+
. Restart each Cassandra node and specify the Producer parameters in the `JVM_EXTRA_OPTS` setting, with each parameter as a comma separated list in the format `parameter=value`.  For more information on the producer parameters, see link:producerParams.adoc[Producer Parameters].  In this example, the most important setting `pulsarServiceUrl` is included.  This points the Cassandra CDC Producer at the Pulser service.  In this case, the host name of the Pulsar service is `schemaregistry` using the **Broker data port** of 6650:
+
[cols="2,2a",options=header]
|===
|Cassandra Version
|CDC Pulsar Producer

|3.11 
|[source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v3-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----

| 4.0 
| [source,language-bash]
----
export JVM_EXTRA_OPTS="-javaagent:/path/to/producer-v4-pulsar-0.1.0-SNAPSHOT-all.jar=pulsarServiceUrl=http://schemaregistry:6650"
----
|===

== Step 2: Install Pulsar

Depending on your organizations needs, there are different distributions of Apache Pulsar to use.  One is the https://pulsar.apache.org/[Apache Pulsar distribution] available from the Apache Software Foundation.  For high availability production systems, another option is https://www.datastax.com/products/luna-streaming[Luna Streaming], a production oriented distribution of Apache Pulsar and engineered to run on Kubernetes.

=== Install Apache Pulsar

Apache Pulsar has provided installation instructions for local, Docker, and Kubernetes based installations.  These are available on the https://pulsar.apache.org/docs/en/standalone/[Pulsar Documentation site].

=== Install Luna Streaming

The DataStax Luna Streaming service provides a production level, secure distribution of Apache Pulsar.  For instructions on how to install Luna Streaming, see either of the following based on your environment:

* https://docs.datastax.com/en/luna/streaming/2.7/quickstart-helm-installs.html[Quick Start for Helm Chart installs]
* https://docs.datastax.com/en/luna/streaming/2.7/quickstart-server-installs.html[Quick Start for Server/VM installs]

== Step 4: Install the Pulsar CSC Source Connector

The following steps will install the Pulsar CSC Source Connector and set up the topics to capture Cassandra CDC events.

. Set the **tenant** and **namespace** where the topics to store the Cassandra CDC events.  For more information, see the Pulsar documentation for https://pulsar.apache.org/docs/en/admin-api-tenants/[Managing Tenants] and https://pulsar.apache.org/docs/en/admin-api-namespaces/[Managing Namespaces].  For this example, we will use the tenant `cassandra` with the namespace `csc` created with the following commands:
+
[source,language-bash]
----
pulsar-admin tenants create cassandra
pulsar-admin namespace create cassandra/csc
----
+
. **(Optional)**.  Topics can be auto-created with the  `set-auto-topic-creation` setting for the namespace being used to store Cassandra CDC events.  This allows for the topics to be automatically generated without having to be manually set.  If running `pulsar-admin` remotely, set the parameter `--admin-url $PULSAR_BROKER_HTTP` `$PULSAR_ADMIN_AUTH` to connect to the remote Pulsar service.
+
In this example, the tenant is `cassandra` and the namespace is `csc`.
+
[source,language-bash]
----
pulsar-admin --admin-url $PULSAR_BROKER_HTTP $PULSAR_ADMIN_AUTH namespaces set-auto-topic-creation cassandra/csc --enable
----
+
. Add the Source Connector file `source-pulsar-<version>-SNAPSHOT.nar` (replacing `<version` with the version being installed) to your Pulsar service by one of two methods:
.. Use a default Connector directory for your Pulsar server.  For more information, see the Apache Pulsar documentation article  https://pulsar.apache.org/docs/en/io-use/#configure-a-default-storage-location-for-a-connector[Configure a default storage location for a connector].  By default, this located `./connectors` in the Pulsar root directory.
.. Upload the Source Connector file anywhere on the Pulsar server.  Note the exact path of the file.
. Add the connector details.  Note that there will be a Source Connector configuration for **each Cassandra table**.  The example below uses `pulsar-admin` to set the Source Connector settings for the Cassandra table `cycling.cyclist_name`.  The most important of these are the following:
.. **tenant** and **namespace**: The **tenant** and **namespace** where the CDC events from the Cassandra table are stored.
.. The **name** of the Source Connector.  Because each Cassandra table requires a Source Connector setting, the **name** of the Source Connector must be unique.
.. **destination-topic-name**: The location for the final Cassandra table CDC data.  The format should be `data-{cassanra-keyname}.{table-name}`.  In the example below, this becomes `data-cycling.cyclist_name`.
.. **source-config**: The **source-config* is in JSON format, and sets the following:
... **contactPoints**: The Cassandra CQL native port to receive Cassandra submissions from.
... **localDc**: The data center used for load balancing.
... **keyspace**:  The Cassandra keyspace.
... **table**: The table CDC data is being captured for.
... **events.topic**: The events topic where the Cassandra CDC data will initially before before verification and deduplication.  The format should be `events-{cassanra-keyname}.{table-name}`.  In the example below, this becomes `events-cycling.cyclist_name`.
... **keyConverter** and **valueConverter**:  Specifies the Pulsar converters used to convert Cassandra keys and JSON data into Pulsar format.
+
In the following example, the following Cassandra information is used:
+
* **Key**: `cycling`
* **Table**: `cyclist_name`
+
This creates the following `pulsar-admin` command, replacing `<version>` with the version of the `.nar` file used.
+
[source,language-bash]
----
pulsar-admin source localrun \
--archive /path/to/source-pulsar-<version>.nar \
--tenant cassandra \
--namespace csc \
--name cassandra-cycling-cyclist-name \
--destination-topic-name data-cycling.cyclist_name \
--source-config '{"contactPoints":"localhost:9042", "localDc":"datacenter1", "keyspace":"cycling", "table":"cyclist_name", "events.topic":"events-cycling.cyclist_name", "key.converter":"com.datastax.oss.pulsar.source.converters.AvroConverter","value.converter":"com.datastax.oss.pulsar.source.converters.JsonConverter"}'
----

== Step 4: Read the Cassandra Data

To read from the gathered data from the Cassandra cluster, create a Pulsar Consumer directed at the specific `destination-topic-name` detailed above.  For more information, see the https://pulsar.apache.org/docs/en/concepts-messaging/#consumers[Apache Pulsar Consumer guide].