apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cl1
spec:
  version: 7.9.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false