== Pass {cdc_pulsar} settings directly to the DataStax Java driver

In your {cdc_pulsar} configuration file, you can directly pass settings to the DataStax Java driver by using the `datastax-java-driver` prefix.
For example:

[source,no-highlight]
----
datastax-java-driver.basic.request.consistency=ALL
----

== Mapping {cdc_pulsar} settings to Java driver properties

The following table identifies functionally equivalent {cdc_pulsar} and DataStax Java driver settings.

NOTE: If you define both in your configuration, the {cdc_pulsar} setting take precedence over the `datastax-java-driver.property-name`.
If you do not provide either in your configuration, {cdc_pulsar} defaults are in effect.

For information about the Java properties, refer to the link:https://docs.datastax.com/en/developer/java-driver-dse/2.3/manual/core/configuration/[DataStax Java driver documentation].

|===
| {csc_pulsar_first} | Using datastax-java-driver prefix

| `contactPoints`
| `datastax-java-driver.basic.contact-points`

| `loadBalancing.localDc`
| `datastax-java-driver.basic.load-balancing-policy.local-datacenter`

| `cloud.secureConnectBundle`
| `datastax-java-driver.basic.cloud.secure-connect-bundle`

| `queryExecutionTimeout`
| `datastax-java-driver.basic.request.timeout`

| `connectionPoolLocalSize`
| `datastax-java-driver.advanced.connection.pool.local.size`

| `compression`
| `datastax-java-driver.advanced.protocol.compression`

| `metricsHighestLatency`
| `datastax-java-driver.advanced.metrics.session.cql-requests.highest-latency`
|===

There is a difference between the {cdc_pulsar}'s `contactPoints` setting and the Java driver's `datastax-java-driver.basic.contact-points`.
For {cdc_pulsar}'s `contactPoints`, the value of the port is appended to every host provided by this setting.
For `datastax-java-driver.basic.contact-points`, you must provide the fully qualified contact points (`host:port`).

By passing in the Java driver's setting, this option gives you more configuration flexibility because you can specify a different port for each host. For example:

[source,no-highlight]
----
datastax-java-driver.basic.contact-points = 127.0.0.1:9042, 127.0.0.2:9042
----

== Java driver reference

For more information, refer to the link:https://docs.datastax.com/en/developer/java-driver/4.3/manual/core/configuration/reference/[Java driver reference configuration] topic.
