runtime:
  log:
    failure_level: warn
git:
  # ensure_git_suffix: false # Enable if necessary -- some git services don’t recognize the URL if it contains the .git extension.
  fetch_concurrency: 10

site:
  title: DataStax Docs
  start_page: cdc-for-cassandra::index.adoc
  robots: disallow

content:
  branches: main # Sources default to this branch if none are specified.
  sources:
  - url: ..
    start_path: docs
    branches: HEAD

antora:
  extensions:
  - '@antora/atlas-extension'
  - '@antora/collector-extension'
  - extensions/assets-processor.js
  - extensions/tailwind-processor.js
  - id: unlisted-pages
    enabled: true
    require: extensions/unlisted-pages-extension.js
    add_to_navigation: false
    unlisted_pages_heading: Orphans

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  - extensions/remote-include-processor.js
  - extensions/svg-macro.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  attributes:
    # BUILT-IN ATTRIBUTES
    # allow-uri-read: '' # Quality-of-life benefit for IntelliJ users. CAUTION: Opens the door to malicious code insertion - must remain disabled in prod build environment.
    # hide-uri-scheme: '' # Consider enabling this attribute to make raw http hyperlinks look cleaner.
    experimental: ''
    idprefix: ''
    idseparator: '-'
    # kroki-fetch-diagram: true
    # kroki-server-url:
    max-include-depth: 10
    page-toclevels: 2@
    sectlinks: ''
    tabs-sync-option: ''
    example-caption: false
    figure-caption: false
    table-caption: false
    xrefstyle: short
    # CUSTOM ATTRIBUTES
    company: 'DataStax'
    trust-center: 'IBM Trust Center'
    trust-center-url: 'https://www.ibm.com/trust'
    trust-center-link: '{trust-center-url}[{trust-center}]'
    support-url: 'https://www.ibm.com/mysupport/s/'
    dsbulk: 'DataStax Bulk Loader (DSBulk)'
    dsbulk-short: 'DSBulk'
    dsbulk-repo: 'https://github.com/datastax/dsbulk'
    astra: 'Astra'
    astra-db: 'Astra DB'
    astra-ui: 'Astra Portal'
    astra-url: 'https://astra.datastax.com'
    astra-ui-link: '{astra-url}[{astra-ui}^]'
    db-classic: 'Astra Managed Clusters'
    db-serverless: 'Serverless (non-vector)'
    db-serverless-vector: 'Serverless (vector)'
    scb: 'Secure Connect Bundle (SCB)'
    scb-short: 'SCB'
    scb-brief: 'Secure Connect Bundle'
    devops-api: 'DevOps API'
    devops-api-ref-url: 'xref:astra-api-docs:ROOT:attachment$devops-api/index.html'
    astra-cli: 'Astra CLI'
    astra-stream: 'Astra Streaming'
    starlight-kafka: 'Starlight for Kafka'
    starlight-rabbitmq: 'Starlight for RabbitMQ'
    sstable-sideloader: '{astra-db} Sideloader'
    zdm: 'Zero Downtime Migration'
    zdm-short: 'ZDM'
    zdm-proxy: 'ZDM Proxy'
    cass-migrator: 'Cassandra Data Migrator (CDM)'
    cass-migrator-short: 'CDM'
    hcd: 'Hyper-Converged Database (HCD)'
    hcd-short: 'HCD'
    dse: 'DataStax Enterprise (DSE)'
    dse-short: 'DSE'
    metrics-collector: 'DSE Metrics Collector'
    mc: 'Mission Control'
    opscenter: 'DSE OpsCenter'
    studio: 'DataStax Studio'
    cass-reg: 'Apache Cassandra(R)'
    cass: 'Apache Cassandra'
    cass-short: 'Cassandra'
    cql: 'Cassandra Query Language (CQL)'
    cql-shell: 'CQL shell'
    cql-console: 'CQL console'
    cql-service: 'CQL Service'
    pulsar-reg: 'Apache Pulsar(TM)'
    pulsar: 'Apache Pulsar'
    pulsar-short: 'Pulsar'
    spark-reg: 'Apache Spark(TM)'
    spark: 'Apache Spark'
    spark-short: 'Spark'
    spark-connect: 'Spark Connect'
    spark-connector: 'Apache Cassandra Spark Connector'
    spark-connector-short: 'Spark Connector'
    kafka-reg: 'Apache Kafka(R)'
    kafka: 'Apache Kafka'
    kafka-short: 'Kafka'
    kafka-connect: 'Kafka Connect'
    kafka-connector: 'DataStax Apache Kafka Connector'
    kafka-connector-short: 'Kafka Connector'
    solr-reg: 'Apache Solr(TM)'
    solr: 'Apache Solr'
    solr-short: 'Solr'
    lucene-reg: 'Apache Lucene(TM)'
    lucene: 'Apache Lucene'
    lucene-short: 'Lucene'
    hadoop-reg: 'Apache Hadoop(R)'
    hadoop: 'Apache Hadoop'
    hadoop-short: 'Hadoop'
    airflow-reg: 'Apache Airflow(R)'
    airflow: 'Apache Airflow'
    airflow-short: 'Airflow'
    maven-reg: 'Apache Maven(TM)'
    maven: 'Apache Maven'
    maven-short: 'Maven'
    flink-reg: 'Apache Flink(R)'
    flink: 'Apache Flink'
    flink-short: 'Flink'
    beam-reg: 'Apache Beam(R)'
    beam: 'Apache Beam'
    beam-short: 'Beam'
    geode-reg: 'Apache Geode(TM)'
    geode: 'Apache Geode'
    geode-short: 'Geode'
    hbase-reg: 'Apache HBase(R)'
    hbase: 'Apache HBase'
    hbase-short: 'HBase'
    kudu-reg: 'Apache Kudu(TM)'
    kudu: 'Apache Kudu'
    kudu-short: 'Kudu'
    phoenix-reg: 'Apache Phoenix(TM)'
    phoenix: 'Apache Phoenix'
    phoenix-short: 'Phoenix'
    zookeeper-reg: 'Apache ZooKeeper(TM)'
    zookeeper: 'Apache ZooKeeper'
    zookeeper-short: 'ZooKeeper'
    asf: 'Apache Software Foundation (ASF)'
    asf-short: 'ASF'
    tinkerpop-reg: 'Apache TinkerPop(TM)'
    tinkerpop: 'Apache TinkerPop'
    tinkerpop-short: 'TinkerPop'
    cloudstack-reg: 'Apache CloudStack(R)'
    cloudstack: 'Apache CloudStack'
    cloudstack-short: 'CloudStack'
    tomcat-reg: 'Apache Tomcat(R)'
    tomcat: 'Apache Tomcat'
    tomcat-short: 'Tomcat'
    ajp: 'Apache JServ Protocol (AJP)'
    ajp-short: 'AJP'
    activemq-reg: 'Apache ActiveMQ(R)'
    activemq: 'Apache ActiveMQ'
    activemq-short: 'ActiveMQ'
    tomee-reg: 'Apache TomEE(TM)'
    tomee: 'Apache TomEE'
    tomee-short: 'TomEE'
    bookkeeper-reg: 'Apache BookKeeper(TM)'
    bookkeeper: 'Apache BookKeeper'
    bookkeeper-short: 'BookKeeper'
    groovy-reg: 'Apache Groovy(TM)'
    groovy: 'Apache Groovy'
    groovy-short: 'Groovy'
    cpp-driver-url: 'https://github.com/datastax/cpp-driver'
    csharp-driver-url: 'https://github.com/datastax/csharp-driver'
    gocql-astra-url: 'https://github.com/datastax/gocql-astra'
    go-driver-url: 'https://github.com/apache/cassandra-gocql-driver'
    cql-proxy-url: 'https://github.com/datastax/cql-proxy'
    java-driver-url: 'https://github.com/apache/cassandra-java-driver'
    nodejs-driver-url: 'https://github.com/datastax/nodejs-driver'
    python-driver-url: 'https://github.com/datastax/python-driver'
    scala-driver-url: 'https://github.com/apache/cassandra-spark-connector'
    cass-driver-cpp-shield: 'image:https://img.shields.io/github/v/tag/datastax/cpp-driver?label=latest[alt="Latest cpp-driver release on GitHub",link="{cpp-driver-url}/tags"]'
    cass-driver-csharp-shield: 'image:https://img.shields.io/nuget/v/CassandraCSharpDriver?label=latest[alt="Latest CassandraCSharpDriver release on NuGet",link="https://www.nuget.org/packages/CassandraCSharpDriver"]'
    cass-driver-go-shield: 'image:https://img.shields.io/github/v/tag/apache/cassandra-gocql-driver?label=latest%20gocql[alt="Latest gocql release on GitHub",link="{go-driver-url}/tags"]'
    cass-driver-java-shield: 'image:https://img.shields.io/github/v/tag/apache/cassandra-java-driver?label=latest[alt="Latest cassandra-java-driver release on GitHub",link="{java-driver-url}/tags"]'
    cass-driver-nodejs-shield: 'image:https://img.shields.io/github/v/tag/datastax/nodejs-driver?label=latest[alt="Latest nodejs-driver release on GitHub",link="{nodejs-driver-url}/tags"]'
    cass-driver-python-shield: 'image:https://img.shields.io/github/v/tag/datastax/python-driver?label=latest[alt="Latest python-driver release on GitHub",link="{python-driver-url}/tags"]'
    cass-driver-scala-shield: 'image:https://img.shields.io/github/v/tag/apache/cassandra-spark-connector?label=latest[alt="Latest cassandra-spark-connector release on GitHub",link="{scala-driver-url}/releases"]'
    data-api: 'Data API'
    csharp-client-api-ref-url: 'xref:astra-api-docs:ROOT:attachment$csharp-client'
    py-client-api-ref-url-2x: 'xref:astra-api-docs:ROOT:attachment$python-client/astrapy'
    ts-client-api-ref-url-2x: 'xref:astra-api-docs:ROOT:attachment$typescript-client'
    java-client-api-ref-url-2x: 'xref:astra-api-docs:ROOT:attachment$java-client'
    python-client-repo-url: 'https://github.com/datastax/astrapy'
    typescript-client-repo-url: 'https://github.com/datastax/astra-db-ts'
    typescript-client-examples-url: '{typescript-client-repo-url}/blob/v2.x/examples'
    java-client-repo-url: 'https://github.com/datastax/astra-db-java'
    csharp-client-repo-url: 'https://github.com/datastax/astra-db-csharp'
    python-client-python-version: '3.8'
    dataapi-java-client-shield: 'image:https://img.shields.io/maven-central/v/com.datastax.astra/astra-db-java.svg?label=latest[alt="Latest astra-db-java release on Maven Central",link="https://search.maven.org/artifact/com.datastax.astra/astra-db-java"]'
    dataapi-python-client-shield: 'image:https://img.shields.io/github/v/tag/datastax/astrapy?label=latest[alt="Latest astrapy release on GitHub",link="{python-client-repo-url}/releases"]'
    dataapi-typescript-client-shield: 'image:https://img.shields.io/github/v/tag/datastax/astra-db-ts?label=latest[alt="Latest astra-db-ts release on GitHub",link="{typescript-client-repo-url}/releases"]'
    dataapi-csharp-client-shield: 'image:https://img.shields.io/github/v/tag/datastax/astra-db-csharp?label=latest[alt="Latest astra-db-csharp release on GitHub",link="{csharp-client-repo-url}/releases"]'
    agent: 'DataStax Agent'
    repair-service: 'Repair Service'
    backup-service: 'Backup Service'
    performance-service: 'Performance Service'
    monitoring-service: 'OpsCenter Monitoring'
    nodesync-service: 'NodeSync Service'
    bestpractice-service: 'Best Practice Service'
    capacity-service: 'Capacity Service'
    lcm: 'Lifecycle Manager (LCM)'
    lcm-short: 'LCM'
    # Antora Atlas
    primary-site-url: https://docs.datastax.com/en
    primary-site-manifest-url: https://docs.datastax.com/en/site-manifest.json

urls:
  latest_version_segment_strategy: redirect:from
  latest_version_segment: 'latest'

ui:
  bundle:
    url: https://github.com/riptano/docs-ui/releases/latest/download/ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # supplemental_files: supplemental-ui

output:
  dir: 'build/site'